# Generated by Django 5.1 on 2024-08-19 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_price_item_price_per_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_per_package',
            new_name='current_price_per_package',
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='sales.item')),
            ],
        ),
    ]
