# Generated by Django 5.1 on 2024-08-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_item_last_updated_at_item_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
