# Generated by Django 5.1 on 2024-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_item_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('MPesa', 'MPesa'), ('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
    ]
