# Generated by Django 5.1 on 2024-08-25 17:42

from django.db import migrations, models



def set_receipt_no(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    for sale in Sale.objects.filter(receipt_no__isnull=True).order_by('id'):
        last_receipt = Sale.objects.order_by('receipt_no').last()
        if last_receipt and last_receipt.receipt_no:
            sale.receipt_no = last_receipt.receipt_no + 1
        else:
            sale.receipt_no = 1
        sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(set_receipt_no),
    ]
