# Generated by Django 5.1 on 2024-08-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
