# Generated by Django 5.1 on 2024-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_receipt_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='receipt_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
