# Generated by Django 5.1 on 2024-08-25 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_dailyreceipt_alter_sale_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreceipt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
