# Generated by Django 3.2.25 on 2024-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_sale_receipt_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
