# Generated by Django 3.2.25 on 2024-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_no',
            field=models.DecimalField(decimal_places=0, max_digits=15, unique=True),
        ),
    ]
