# Generated by Django 3.2.25 on 2024-10-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_sale_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_no',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('receipt_no', 'item')},
        ),
    ]
