# Generated by Django 5.1 on 2024-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_table_sale_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
