# Generated by Django 5.1 on 2024-12-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_table_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_per_package_type',
        ),
    ]
