# Generated by Django 5.1 on 2024-12-29 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_business_admin_business_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
