# Generated by Django 5.1 on 2024-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_remove_business_owner_business_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Free', 'Free')], max_length=20),
        ),
    ]
