# Generated by Django 5.1 on 2025-01-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/default-profile.png', upload_to='profile_pictures/'),
        ),
    ]
